@FlightDataAnalysis_HostAddress = http://localhost:5159

GET {{FlightDataAnalysis_HostAddress}}/api/v1/flights
Accept: application/json

###


GET {{FlightDataAnalysis_HostAddress}}/api/v1/flights/1
Accept: application/json

###

GET {{FlightDataAnalysis_HostAddress}}/api/v1/flights/options
Accept: application/json

###


GET {{FlightDataAnalysis_HostAddress}}/api/v1/flights/paged?pageNumber=1&pageSize=10
Accept: application/json

###


GET {{FlightDataAnalysis_HostAddress}}/api/v1/flight-analysis
Accept: application/json

###


